# Generated by Django 3.2.12 on 2023-08-23 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_follwerscount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FollwersCount',
            new_name='FollowersCount',
        ),
    ]
